{{- if or .Values.controlPlane.vault.enabled .Values.dataPlane.vault.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.controlPlane.vault.tokenSecretName | default .Values.dataPlane.vault.tokenSecretName }}
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "edc.labels" . | nindent 4 }}
type: Opaque
data:
  {{ .Values.controlPlane.vault.tokenSecretKey | default .Values.dataPlane.vault.tokenSecretKey }}: {{ printf "your-vault-token-here" | b64enc }}
{{- end }} 